name: INPUT TEST

on:
  workflow_dispatch:
    inputs:
      SA_name:
        description: 'storageAccounts_name'
        required: true

jobs:
 SA_deploy:
    name: SA_Deploy
    runs-on: ubuntu-latest
    steps:
        # Checkout code
      - uses: actions/checkout@main
        # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Deploy StorageAccount Template
      - name: Run StorageAccount deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG4 }}
          template: ./ARM_Template/ARMTemplate_StorageAccount.json
          parameters: ./ARM_Template/INPUT_ARM_Template_Parameter.json storageAccounts_name=${{ github.event.inputs.SA_name }}

 PE_deploy:
    name: PE_Deploy
    needs: SA_Deploy
    runs-on: ubuntu-latest
    steps:
        # Checkout code
      - uses: actions/checkout@main
        # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Deploy PrivateEndpoint Template
      - name: Run PrivateEndpoint deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG4 }}
          template: ./ARM_Template/DNS_ARMTemplate_PrivateEndpoint.json
          parameters: ./ARM_Template/INPUT_ARM_Template_Parameter.json storageAccounts_name=${{ github.event.inputs.SA_name }}
