 name: logicapps input
 
 on:
   workflow_dispatch:
     inputs:
       logicapps_input:
         description: 'logicapps input'
         required: false
         default: 'xxxxx'
 
 jobs:
   logicapps_job:
     runs-on: ubuntu-18.04
     timeout-minutes: 60
     steps:
       - run: echo "${{ github.event.inputs.logicapps_input }}"
