name: StorageAccount

on:
  workflow_dispatch:

jobs:
 deployment:
    runs-on: ubuntu-latest
    steps:
        # Checkout code
      - uses: actions/checkout@main

        # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy StorageAccount template
      - name: Run StorageAccount deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./ARM_Template/ARMTemplate_StorageAccount.json
          parameters: ./ARM_Template/ARMTemplateParameters_StorageAccount.json

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
