name: ADF_Linked_TEST

on:
  workflow_dispatch:

jobs:
 deployment:
    runs-on: ubuntu-latest
    steps:
        # Checkout code
      - uses: actions/checkout@main

        # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run LinkedTemplate deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./linkedTemplates/ArmTemplate_master.json
          parameters: ./linkedTemplates/ArmTemplateParameters_master.json

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
