name: ADF

on:
  workflow_dispatch:

jobs:
 deployment:
    runs-on: ubuntu-latest
    steps:
        # Checkout code
      - uses: actions/checkout@main

        # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Factory template
      - name: Run Factory deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./factory/kansai-adf-ueda-dev_ARMTemplateForFactory.json
          parameters: ./factory/kansai-adf-ueda-dev_ARMTemplateParametersForFactory.json

        # Deploy linked template
      - name: Run linked deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./linkedTemplates/ArmTemplate_master.json
          parameters: ./linkedTemplates/ArmTemplateParameters_master.json

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./ARMTemplateForFactory.json
          parameters: ./ARMTemplateParametersForFactory.json

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
